version: "3.0"
services:
  faraway-app:
    stdin_open: true
    tty: true
    # same as -it passed in docker run cmd
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=faraway
    ports:
      - "8080:80"
    env_file:
      - ./.env